id: P57FFCEE0
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni
  language: nl
  description: 'Texts by and about Buddha Śākyamuni (shākya thub pa):'
  volume:
    62a733cde477455fae79a3a5846fcb52:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Guru Yoga
    cff2aae7bc914e1c959b6f0241702a84:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Guru Yoga
    892df07da48e47f1b25d4b09b342bffc:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Praise
    3e3dd6b4b46a488793f760d80347d6ba:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    7aa282afcc6a4daf9e8d9485f177e6cd:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    bb69809394c849fdbdc801c321dad503:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    28e448b887644addbec2abdae4dca074:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    56a2a0e7ab4242c197ad4b2f244ed3cd:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
    ba5a41b684894dc29fff47c6180e670c:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
created_at: '2022-03-01T02:12:34.858068'
last_modified_at: '2022-03-01T02:12:34.858071'
